# Generated by Django 5.2.7 on 2026-01-14 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gsr001Search',
            fields=[
                ('idobj', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'action_sociale"."gsr001_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gsr002GuichetSocialRegional',
            fields=[
                ('idobj', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('comnom', models.CharField(max_length=100)),
                ('nom_gsr', models.CharField(max_length=60, unique=True)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('form_prise_contact', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=60)),
                ('informations', models.CharField(max_length=200)),
                ('google_maps', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
            ],
            options={
                'db_table': 'action_sociale"."gsr002_guichet_social_regional',
                'managed': False,
            },
        ),
    ]
