# Generated by Django 4.0.5 on 2023-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[("CREATE SCHEMA IF NOT EXISTS general;")],
            reverse_sql=[("DROP SCHEMA general CASCADE;")],
        ),
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('idobj', models.UUIDField(primary_key=True, serialize=False)),
                ('numcad', models.BigIntegerField()),
                ('cadnom', models.CharField(max_length=50)),
                ('numcom', models.BigIntegerField()),
                ('nufeco', models.BigIntegerField()),
                ('comnom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'general"."la02_cadastres',
            },
        ),
    ]
