# Generated by Django 4.0.5 on 2024-04-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='immeublesadressessearch',
            table='searchtables"."search_immeubles_adresses',
        ),
    ]
