# Generated by Django 5.2.7 on 2026-01-14 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0002_alter_immeublesadressessearch_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo9Immeubles',
            fields=[
                ('idobj', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nummai', models.CharField(max_length=7)),
                ('numcad', models.IntegerField(db_column='numcom')),
                ('cadastre', models.CharField(max_length=50)),
                ('idmai', models.CharField(db_column='id', max_length=50)),
                ('egrid', models.CharField(max_length=14)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'mensuration"."mo9_immeubles',
                'managed': False,
            },
        ),
    ]
