# Generated by Django 5.2.7 on 2026-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RfcenAdresse',
            fields=[
                ('ase_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('akt_name', models.CharField(max_length=256)),
                ('akt_vorname', models.CharField(max_length=256)),
                ('akt_ase_typ', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'RFCEN"."ADRESSE',
                'managed': False,
            },
        ),
    ]
