# Generated by Django 5.2.7 on 2026-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre_foncier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recht',
            fields=[
                ('rht_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lst_id', models.CharField(max_length=8)),
                ('lst_typ', models.CharField(max_length=1)),
                ('gdk_last', models.CharField(max_length=12)),
                ('esta_last', models.CharField(max_length=4)),
                ('art_last', models.CharField(max_length=1)),
                ('gdk_recht', models.CharField(max_length=12)),
                ('esta_recht', models.CharField(max_length=4)),
                ('loesch_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'RF_SITN"."RECHT',
                'managed': False,
            },
        ),
    ]
