# Generated by Django 5.2.7 on 2026-01-14 14:29

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import ppe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS ppe;'),
        migrations.CreateModel(
            name='GeoshopCadastreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField()),
                ('date_processed', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=2056)),
            ],
            options={
                'db_table': 'ppe_static"."geoshop_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdresseFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personne', models.CharField(choices=[('pp', 'Personne physique'), ('pm', 'Personne morale')], default='pp', max_length=50)),
                ('nom_raison_sociale', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=ppe.models.rename_pdf_accord, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
            options={
                'db_table': 'ppe"."adresse_facturation',
                'ordering': ['nom_raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='ContactPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('no_tel', models.CharField(max_length=15)),
                ('raison_sociale', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'ppe"."contact_principal',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Geolocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
            ],
            options={
                'db_table': 'ppe"."geolocalisation',
            },
        ),
        migrations.CreateModel(
            name='Notaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ppe"."notaire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Signataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ppe"."signataire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DossierPPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(max_length=16)),
                ('cadastre', models.CharField(max_length=50)),
                ('numcad', models.IntegerField()),
                ('nummai', models.CharField(max_length=10)),
                ('coord_E', models.IntegerField()),
                ('coord_N', models.IntegerField()),
                ('statut', models.CharField(choices=[('P', 'En préparation'), ('S', 'Soumis'), ('T', 'En traitement'), ('C', 'Corrections requises'), ('R', 'Rejeté'), ('V', 'Dossier papier validé')], default='P', max_length=20)),
                ('type_dossier', models.CharField(choices=[('C', 'Constitution'), ('R', 'Révision'), ('M', 'Modification'), ('I', 'Indéfini')], max_length=20)),
                ('revision_jouissances', models.CharField(blank=True, default=None, max_length=3)),
                ('elements_rf_identiques', models.CharField(blank=True, default=None, max_length=3)),
                ('nouveaux_droits', models.CharField(blank=True, default=None, max_length=3)),
                ('ref_geoshop', models.CharField(blank=True, default=None, max_length=20)),
                ('ref_dossier_initial', models.IntegerField(null=True)),
                ('aff_infolica', models.IntegerField(null=True)),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(auto_now=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(auto_now=True, verbose_name='Date de validation')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
                ('adresse_facturation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.adressefacturation')),
                ('contact_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.contactprincipal')),
                ('notaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.notaire')),
                ('signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.signataire')),
            ],
            options={
                'db_table': 'ppe"."dossier_ppe',
            },
        ),
        migrations.CreateModel(
            name='Zipfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipfile', models.FileField(upload_to=ppe.models.unique_folder_path, validators=[django.core.validators.FileExtensionValidator(['zip'])])),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Date de chargement')),
                ('file_statut', models.CharField(choices=[('CAA', 'Contrôle automatique : archivé'), ('CAC', 'Contrôle automatique : en cours'), ('CAE', 'Contrôle automatique : erreurs à corriger'), ('ERR', 'Contrôle automatique : erreur interne'), ('CAV', 'Contrôle automatique : validé'), ('CMC', 'Contrôle manuel : en cours'), ('CME', 'Contrôle manuel : erreurs à corriger'), ('CMV', 'Contrôle manuel : validé'), ('DPV', 'Dossier papier validé')], default='CAC', max_length=3)),
                ('dossier_ppe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='zipfiles', to='ppe.dossierppe')),
            ],
            options={
                'db_table': 'ppe"."zipfile',
                'ordering': ['-upload_date'],
            },
        ),
    ]
