# Generated by Django 5.0.7 on 2024-10-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.IntegerField(primary_key=True, serialize=False)),
                ('type_contact', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=30)),
                ('fonction', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DossierPPE',
            fields=[
                ('id_dossier', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('EGRID', models.CharField(max_length=14)),
                ('cadastre', models.CharField(max_length=50)),
                ('numcad', models.IntegerField()),
                ('nummai', models.CharField(max_length=10)),
                ('coord_E', models.IntegerField()),
                ('coord_N', models.IntegerField()),
                ('statut', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
    ]
