# Generated by Django 5.1.2 on 2024-10-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personne', models.CharField(choices=[('pp', 'Personne physique'), ('pm', 'Personne morale')], default='pp', max_length=50)),
                ('nom_raison_sociale', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no_tel', models.CharField(max_length=15)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom_raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='ContactPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politesse', models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Me', 'Maître'), ('A', '')], default='A', max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('raison_sociale', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('no_tel', models.CharField(max_length=15)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_document', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politesse', models.CharField(default='Me', max_length=2)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('raison_sociale', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('no_tel', models.CharField(max_length=15)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('raison_sociale', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('no_tel', models.CharField(max_length=15)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_rue', models.CharField(blank=True, max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DossierPPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(max_length=16)),
                ('egrid', models.CharField(blank=True, max_length=14)),
                ('cadastre', models.CharField(max_length=50)),
                ('numcad', models.IntegerField()),
                ('nummai', models.CharField(max_length=10)),
                ('coord_E', models.IntegerField()),
                ('coord_N', models.IntegerField()),
                ('statut', models.CharField(choices=[('P', 'En projet'), ('S', 'Soumis'), ('T', 'En traitement'), ('R', 'Rejeté')], max_length=20)),
                ('type_dossier', models.CharField(choices=[('C', 'Constitution'), ('R', 'Révision'), ('M', 'Modification')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(auto_now=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(auto_now=True, verbose_name='Date de validation')),
                ('accord_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.document')),
                ('adresse_facturation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.adressefacturation')),
                ('contact_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.contactprincipal')),
                ('notaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.notaire')),
                ('signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.signataire')),
            ],
        ),
    ]
