# Generated by Django 5.2.7 on 2026-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='elements_rf_identiques',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='nouveaux_droits',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='ref_geoshop',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='revision_jouissances',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
