# Generated by Django 5.0.7 on 2024-10-31 09:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('idobj', models.UUIDField(primary_key=True, serialize=False)),
                ('numcad', models.BigIntegerField()),
                ('cadnom', models.CharField(max_length=50)),
                ('numcom', models.BigIntegerField()),
                ('nufeco', models.BigIntegerField()),
                ('comnom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ppe"."la02_cadastres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('idobj', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('comnom', models.CharField(max_length=100)),
                ('numcom', models.BigIntegerField()),
                ('nufeco', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'ppe"."la3_limites_communales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mo9Immeubles',
            fields=[
                ('idobj', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nummai', models.CharField(max_length=7)),
                ('numcad', models.IntegerField(db_column='numcom')),
                ('cadastre', models.CharField(max_length=50)),
                ('idmai', models.CharField(db_column='id', max_length=50)),
                ('egrid', models.CharField(max_length=14)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'ppe"."mo9_immeubles',
                'managed': False,
            },
        ),
    ]
