# Generated by Django 5.0.7 on 2024-10-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fonction',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.contact')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.dossierppe')),
            ],
        ),
    ]
