# Generated by Django 5.2.7 on 2026-01-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0002_alter_dossierppe_elements_rf_identiques_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adressefacturation',
            options={'ordering': ['nom_raison_sociale'], 'verbose_name': 'Adresse facturation', 'verbose_name_plural': 'Adresses facturation'},
        ),
        migrations.AlterModelOptions(
            name='contactprincipal',
            options={'ordering': ['nom'], 'verbose_name': 'Contact principal', 'verbose_name_plural': 'Contacts principaux'},
        ),
        migrations.AlterModelOptions(
            name='dossierppe',
            options={'verbose_name': 'Dossier PPE', 'verbose_name_plural': 'Dossiers PPE'},
        ),
        migrations.AlterModelOptions(
            name='notaire',
            options={'ordering': ['nom'], 'verbose_name': 'Notaire', 'verbose_name_plural': 'Notaires'},
        ),
        migrations.AlterModelOptions(
            name='signataire',
            options={'ordering': ['nom'], 'verbose_name': 'Signataire', 'verbose_name_plural': 'Signataires'},
        ),
    ]
