# Generated by Django 5.0.7 on 2024-10-31 14:42

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point

class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0002_cadastre_commune_mo9immeubles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastre',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Mo9Immeubles',
        ),
        migrations.AddField(
            model_name='dossierppe',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(1,1, srid=4326)),
            preserve_default=False,
        ),
    ]
