# Generated by Django 5.0.7 on 2024-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0002_remove_contact_fonction_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossierppe',
            old_name='EGRID',
            new_name='egrid',
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de création'),
        ),
    ]
