# Generated by Django 5.0.7 on 2024-10-31 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0003_delete_cadastre_delete_commune_delete_mo9immeubles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=2056),
        ),
    ]
