# Generated by Django 5.2.7 on 2026-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0003_alter_adressefacturation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='aff_infolica',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
