# Generated by Django 5.1.4 on 2024-12-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0004_alter_dossierppe_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactprincipal',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='notaire',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='signataire',
            options={'ordering': ['nom']},
        ),
    ]
