# Generated by Django 5.2.7 on 2026-02-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0005_alter_zipfile_file_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='type_dossier',
            field=models.CharField(choices=[('C', 'Constitution'), ('R', 'Révision'), ('M', 'Modification'), ('I', 'Indéfini')], default='I', max_length=20),
        ),
    ]
