# Generated by Django 5.1.4 on 2025-01-23 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0005_alter_contactprincipal_options_alter_notaire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
            ],
        ),
    ]
