# Generated by Django 5.1.4 on 2025-02-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0006_geolocalisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressefacturation',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='contactprincipal',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='contactprincipal',
            name='localite',
        ),
        migrations.RemoveField(
            model_name='contactprincipal',
            name='no_rue',
        ),
        migrations.RemoveField(
            model_name='contactprincipal',
            name='npa',
        ),
        migrations.RemoveField(
            model_name='contactprincipal',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='contactprincipal',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='notaire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='notaire',
            name='no_tel',
        ),
        migrations.RemoveField(
            model_name='notaire',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='notaire',
            name='politesse',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='no_tel',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='pays',
        ),
    ]
