# Generated by Django 5.1.4 on 2025-02-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0007_remove_adressefacturation_pays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressefacturation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adressefacturation',
            name='no_tel',
        ),
    ]
