# Generated by Django 5.2.7 on 2026-03-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0007_alter_zipfile_file_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='statut',
            field=models.CharField(choices=[('A', 'Abandonné'), ('C', 'En correction'), ('E', 'Envoyé'), ('P', 'En préparation'), ('T', 'En traitement'), ('V', 'Validé')], default='P', max_length=20),
        ),
    ]
