# Generated by Django 5.2.7 on 2026-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0008_alter_dossierppe_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='ref_dossier_initial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
