# Generated by Django 5.1.7 on 2025-03-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0008_remove_adressefacturation_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_document', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='temp/')),
            ],
        ),
        migrations.AlterField(
            model_name='contactprincipal',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='id_unique',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='statut',
            field=models.CharField(choices=[('P', 'En projet'), ('S', 'Soumis'), ('T', 'En traitement'), ('R', 'Rejeté')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='accord_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.accordfrais'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
