# Generated by Django 5.1.4 on 2025-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0009_accordfrais_alter_contactprincipal_raison_sociale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaire',
            name='raison_sociale',
        ),
        migrations.RemoveField(
            model_name='signataire',
            name='raison_sociale',
        ),
    ]
