# Generated by Django 5.1.4 on 2025-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0010_remove_notaire_raison_sociale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordfrais',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
