# Generated by Django 5.1.4 on 2025-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0011_alter_accordfrais_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierppe',
            name='accord_frais',
        ),
        migrations.AddField(
            model_name='adressefacturation',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.DeleteModel(
            name='AccordFrais',
        ),
    ]
