# Generated by Django 5.1.4 on 2025-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0012_remove_dossierppe_accord_frais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressefacturation',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
