# Generated by Django 5.1.4 on 2025-04-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0013_alter_adressefacturation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprincipal',
            name='politesse',
        ),
        migrations.RemoveField(
            model_name='dossierppe',
            name='egrid',
        ),
    ]
