# Generated by Django 5.1.4 on 2025-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0014_remove_contactprincipal_politesse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipfile', models.FileField(upload_to='zips/')),
            ],
        ),
    ]
