# Generated by Django 5.1.4 on 2025-06-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0015_zipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierppe',
            name='elements_rf_identiques',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='dossierppe',
            name='nouveaux_droits',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='dossierppe',
            name='revision_jouissances',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='zipfile',
            name='dossier_ppe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppe.dossierppe'),
        ),
        migrations.AddField(
            model_name='zipfile',
            name='file_statut',
            field=models.CharField(blank=True, choices=[('A', 'Dossier remplacé et archivé'), ('E', 'Erreurs bloquantes à corriger'), ('C', 'Vérification automatique en cours'), ('V', "Dossier validé. Il n'est plus possible de le modifier")], max_length=75),
        ),
        migrations.AddField(
            model_name='zipfile',
            name='upload_date',
            field=models.DateField(auto_now=True, verbose_name='Date de chargement'),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='zipfile',
            field=models.FileField(upload_to='files/zips/'),
        ),
    ]
