# Generated by Django 5.1.4 on 2025-07-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0016_dossierppe_elements_rf_identiques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierppe',
            name='ref_geoshop',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='dossier_ppe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.dossierppe'),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='file_statut',
            field=models.CharField(choices=[('A', 'Dossier remplacé et archivé'), ('C', 'Vérification automatique en cours'), ('E', 'Erreurs bloquantes à corriger'), ('P', 'Préparation du dossier'), ('V', "Dossier validé. Il n'est plus possible de le modifier")], default='P', max_length=75),
        ),
    ]
