# Generated by Django 5.1.4 on 2025-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0017_dossierppe_ref_geoshop_alter_zipfile_dossier_ppe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='upload_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de chargement'),
        ),
    ]
