# Generated by Django 5.1.4 on 2025-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0018_alter_zipfile_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprincipal',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='elements_rf_identiques',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='nouveaux_droits',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='ref_geoshop',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='revision_jouissances',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
    ]
