# Generated by Django 5.1.4 on 2025-09-18 14:23

import ppe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0019_alter_contactprincipal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierppe',
            name='ref_dossier_initial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adressefacturation',
            name='file',
            field=models.FileField(upload_to=ppe.models.rename_pdf_accord),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='file_statut',
            field=models.CharField(choices=[('CMA', 'Contrôle automatique : archivé'), ('CAC', 'Contrôle automatique : en cours'), ('CAE', 'Contrôle automatique : erreurs à corriger'), ('CAP', 'Contrôle automatique : en attente'), ('CAV', 'Contrôle automatique : validé'), ('CMC', 'Contrôle manuel : en cours'), ('CME', 'Contrôle manuel : erreurs à corriger'), ('CMV', 'Contrôle manuel : validé')], default='CAC', max_length=3),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='zipfile',
            field=models.FileField(upload_to=ppe.models.unique_folder_path),
        ),
    ]
