# Generated by Django 5.1.4 on 2025-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0020_dossierppe_ref_dossier_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierppe',
            name='ref_dossier_initial',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
