# Generated by Django 5.2.7 on 2025-12-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0022_alter_dossierppe_ref_dossier_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierppe',
            name='aff_infolica',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dossierppe',
            name='statut',
            field=models.CharField(choices=[('P', 'En préparation'), ('S', 'Soumis'), ('T', 'En traitement'), ('C', 'Corrections requises'), ('R', 'Rejeté'), ('V', 'Dossier papier validé')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='file_statut',
            field=models.CharField(choices=[('CMA', 'Contrôle automatique : archivé'), ('CAC', 'Contrôle automatique : en cours'), ('CAE', 'Contrôle automatique : erreurs à corriger'), ('ERR', 'Contrôle automatique : erreur interne'), ('CAV', 'Contrôle automatique : validé'), ('CMC', 'Contrôle manuel : en cours'), ('CME', 'Contrôle manuel : erreurs à corriger'), ('CMV', 'Contrôle manuel : validé'), ('DPV', 'Dossier papier validé')], default='CAC', max_length=3),
        ),
    ]
