# Generated by Django 5.2.7 on 2025-12-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0023_dossierppe_aff_infolica_alter_dossierppe_statut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipfile',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='dossier_ppe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='zipfiles', to='ppe.dossierppe'),
        ),
        migrations.AlterField(
            model_name='zipfile',
            name='file_statut',
            field=models.CharField(choices=[('CAA', 'Contrôle automatique : archivé'), ('CAC', 'Contrôle automatique : en cours'), ('CAE', 'Contrôle automatique : erreurs à corriger'), ('ERR', 'Contrôle automatique : erreur interne'), ('CAV', 'Contrôle automatique : validé'), ('CMC', 'Contrôle manuel : en cours'), ('CME', 'Contrôle manuel : erreurs à corriger'), ('CMV', 'Contrôle manuel : validé'), ('DPV', 'Dossier papier validé')], default='CAC', max_length=3),
        ),
    ]
