# Generated by Django 4.0.5 on 2023-07-19 12:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_historisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisonreunion',
            name='id_operation',
        ),
        migrations.RemoveField(
            model_name='otheroperation',
            name='id_operation',
        ),
        migrations.AddField(
            model_name='balance',
            name='destination_ddp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='divisonreunion',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel_historisation.operation', verbose_name='operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='old_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otheroperation',
            name='bfs_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='otheroperation',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel_historisation.operation', verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='complement',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
