# Generated by Django 4.0.5 on 2023-07-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_historisation', '0002_remove_divisonreunion_id_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='id_division',
        ),
        migrations.AddField(
            model_name='balance',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel_historisation.operation', verbose_name='division'),
        ),
    ]
