# Generated by Django 4.0.5 on 2023-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_historisation', '0003_remove_balance_id_division_balance_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='current_destination',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='destination_rp',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='source_origin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='source_rp',
            field=models.BooleanField(null=True),
        ),
    ]
