# Generated by Django 4.0.5 on 2024-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcel_historisation", "0004_alter_balance_current_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="infolica_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
