# Generated by Django 4.0.5 on 2024-11-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    CREATE_SQL = """
      CREATE OR REPLACE VIEW parcel_historisation.v_source_no_destination AS
        SELECT src.source
        FROM parcel_historisation.balance src
        LEFT JOIN parcel_historisation.balance dst
        ON src.source = dst.destination
        WHERE dst.destination is null
        GROUP BY src.source ;
      CREATE OR REPLACE VIEW parcel_historisation.v_destination_no_source AS
        SELECT dst.destination 
        FROM parcel_historisation.balance src
        RIGHT JOIN parcel_historisation.balance dst
        ON src.source = dst.destination
        WHERE src.source is null
        GROUP BY dst.destination
    """

    DROP_SQL = """
      DROP VIEW IF EXISTS parcel_historisation.v_source_no_destination;
      DROP VIEW IF EXISTS parcel_historisation.v_destination_no_source;
    """

    dependencies = [
        ('parcel_historisation', '0005_balance_is_ddp_operation_infolica_no'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        ),
    ]
