# Generated by Django 4.0.5 on 2024-03-27 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fo01Arrondissement',
            fields=[
                ('idobj', models.UUIDField(primary_key=True, serialize=False)),
                ('inspecteur', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'foret"."fo_arrondissements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fo02Cantonnement',
            fields=[
                ('idobj', models.UUIDField(primary_key=True, serialize=False)),
                ('titulaire', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'foret"."fo_cantonnements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fo11UniteGestionForprivee',
            fields=[
                ('idobj', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
            ],
            options={
                'db_table': 'foret"."fo11_unite_gestion_forprivees',
                'managed': False,
            },
        ),
    ]
