# Generated by Django 5.2.7 on 2026-07-21 13:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'panoview_sequence',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanoramaItem',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(dim=3, srid=2056)),
                ('captured_at', models.DateTimeField()),
                ('azimuth', models.FloatField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('image_name', models.CharField(max_length=255)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='panoview.sequence')),
            ],
            options={
                'db_table': 'panoview_item',
                'ordering': ['sequence_id', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('sequence', 'rank'), name='panoview_item_unique_sequence_rank')],
                'managed': False,
            },
        ),
    ]
