# Generated by Django 4.0.5 on 2024-02-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL('DROP TEXT SEARCH CONFIGURATION IF EXISTS public.fr cascade;'),
        migrations.RunSQL('CREATE TEXT SEARCH CONFIGURATION public.fr (COPY=simple)'),
        migrations.RunSQL('ALTER TEXT SEARCH CONFIGURATION public.fr ALTER MAPPING FOR hword, hword_part, word WITH public.unaccent, simple'),
    ]
